"""The controls for what a pose model IS, how it is fed, and what runs it.

One widget, used by the live tracking dialog and by the offline retrack dialog,
because a retrack that cannot express what the live run did cannot reproduce
it. Same widgets, same config keys, one translation, which is the only way the
two stay comparable as either changes.

Three rows, in the order the questions actually arise:

* **the model card**: what the file says it is. Family, body parts,
  identities, trained input, channels. Read from the model's own config, so it
  is answerable before anything is loaded and on a machine that could not load
  it at all. Where the project contradicts the file, the difference is shown.
* **the input row**: how the frame becomes the model's input. Fields the
  chosen mode does not use are ABSENT rather than greyed: a control that
  cannot do anything is a question the operator should not be asked.
* **the engine row**: which runtime runs it, on what device, at what
  precision, and a button to build the engine now rather than at Record.

And a summary line generated by the REAL resolvers, the same
``resolve_runtime`` the tracker calls and the same crop refusal, so it cannot
promise something the run will not do.

See ``docs/pose_runtime_and_input_plan.html`` §5 (P6).
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from PySide6 import QtCore, QtWidgets
from PySide6.QtWidgets import (QCheckBox, QComboBox, QDoubleSpinBox, QFormLayout,
                               QHBoxLayout, QLabel, QLineEdit, QPushButton,
                               QSpinBox, QVBoxLayout, QWidget)

from tools.offline_analysis.analyze import engine_export as _engines
from tools.offline_analysis.engine.trackers import crop_refusal as _crop_refusal
from tools.offline_analysis.engine.trackers import (MODE_CROP_TRACK,
                                                    MODE_FULL,
                                       MODE_LETTERBOX)
from tools.offline_analysis.engine.trackers import ModelInfo

#: What each input mode is for, in the words of the person choosing it.
_MODE_HELP = {
    MODE_FULL: "the frame as it is, what this app has always done",
    MODE_LETTERBOX: ("scaled and padded to one shape, so arenas of different "
                     "sizes can share one model"),
    MODE_CROP_TRACK: ("a window of the training size, cut at native resolution "
                      "and following the animal, the only correct mode for a "
                      "model trained on crops"),
}

_MUTED = "color:#9aa3b4; font-size:11px;"


class PoseEnginePanel(QWidget):
    """Model card + input mode + engine, for one backend at a time."""

    changed = QtCore.Signal()

    def __init__(self, parent=None, *, backend: str = "sleap",
                 compact: bool = False):
        super().__init__(parent)
        self._backend = backend
        self._model_path = ""
        self._n_animals = 1
        #: The names of those animals, when the run has any. With them, N
        #: animals means N crop windows; without them, crop-track is
        #: single-animal and refuses the combination.
        self._identities: list = []
        self._build(compact)
        # Through `set_backend`, not by assignment: the engine list IS the
        # backend's, and a panel built without it has an empty combo whose
        # `currentData()` is None, which reads as "auto" and silently
        # discards whatever the project had saved.
        self.set_backend(backend)

    # ── construction ─────────────────────────────────────────────────────────

    def _build(self, compact: bool) -> None:
        outer = QVBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0)
        outer.setSpacing(4)

        self._card = QLabel("")
        self._card.setWordWrap(True)
        self._card.setStyleSheet(_MUTED)
        outer.addWidget(self._card)

        form = QFormLayout()
        form.setContentsMargins(0, 0, 0, 0)
        form.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        outer.addLayout(form)

        # ── input ────────────────────────────────────────────────────────────
        self._mode = QComboBox()
        for mode in (MODE_FULL, MODE_LETTERBOX, MODE_CROP_TRACK):
            self._mode.addItem(mode, mode)
        self._mode.setToolTip(
            "How the box's frame becomes the model's input.\n"
            + "\n".join(f"{k}, {v}" for k, v in _MODE_HELP.items()))
        self._mode.currentIndexChanged.connect(self._on_change)
        form.addRow("Input:", self._mode)

        self._window_row = QWidget()
        wr = QHBoxLayout(self._window_row)
        wr.setContentsMargins(0, 0, 0, 0)
        self._win_w = QSpinBox()
        self._win_h = QSpinBox()
        for box in (self._win_w, self._win_h):
            box.setRange(0, 4096)
            box.setSpecialValueText("from the model")
            box.setMaximumWidth(120)
            box.valueChanged.connect(self._on_change)
        self._win_w.setToolTip(
            "Training window width in pixels. 0 takes it from the model's own\n"
            "config, a model can keep its crop in the DATASET instead, and\n"
            "then only the training script knows and it has to be typed.")
        wr.addWidget(self._win_w)
        wr.addWidget(QLabel("x"))
        wr.addWidget(self._win_h)
        wr.addStretch(1)
        self._window_label = "Window:"
        form.addRow(self._window_label, self._window_row)

        self._crop_row = QWidget()
        cr = QHBoxLayout(self._crop_row)
        cr.setContentsMargins(0, 0, 0, 0)
        self._conf = QDoubleSpinBox()
        self._conf.setRange(0.0, 1.0)
        self._conf.setSingleStep(0.05)
        self._conf.setDecimals(2)
        self._conf.setValue(0.20)
        self._conf.setToolTip(
            "Confidence at which a keypoint is worth steering the window by.\n"
            "It changes how the result is READ, not what the network is fed.")
        cr.addWidget(QLabel("follow ≥"))
        cr.addWidget(self._conf)
        self._good = QSpinBox()
        self._good.setRange(1, 50)
        self._good.setValue(3)
        self._good.setToolTip(
            "Confident keypoints needed before the frame counts as tracked.")
        cr.addWidget(QLabel("min kp"))
        cr.addWidget(self._good)
        self._reacquire = QCheckBox("re-acquire")
        self._reacquire.setChecked(True)
        self._reacquire.setToolTip(
            "When the window loses the animal, try one more window per frame\n"
            "until it finds it again. One extra inference, not a search.")
        cr.addWidget(self._reacquire)
        cr.addStretch(1)
        for w in (self._conf, self._good):
            w.valueChanged.connect(self._on_change)
        self._reacquire.toggled.connect(self._on_change)
        form.addRow("Follow:", self._crop_row)

        # ── engine ───────────────────────────────────────────────────────────
        self._engine = QComboBox()
        self._engine.currentIndexChanged.connect(self._on_change)
        form.addRow("Engine:", self._engine)

        self._device = QComboBox()
        self._device.setEditable(True)          # cuda:1 on a multi-GPU host
        self._device.addItems(["auto", "cuda", "cpu"])
        self._device.setToolTip(
            "Where the model runs. Editable, type e.g. cuda:1 to pin this "
            "box to the second GPU.")
        self._device.currentTextChanged.connect(self._on_change)
        form.addRow("Device:", self._device)

        self._precision = QComboBox()
        self._precision.addItems(["fp32", "fp16"])
        self._precision.setToolTip(
            "Weight precision. fp16 roughly halves memory and speeds "
            "inference on a CUDA GPU, measured at 0.07 px mean and 1.97 px "
            "MAXIMUM difference from fp32, so check it against fp32 before "
            "trusting it for published numbers. It is recorded either way.")
        self._precision.currentTextChanged.connect(self._on_change)
        form.addRow("Precision:", self._precision)

        self._centroid_row = QWidget()
        cro = QHBoxLayout(self._centroid_row)
        cro.setContentsMargins(0, 0, 0, 0)
        self._centroid = QLineEdit()
        self._centroid.setPlaceholderText("top-down centroid model folder")
        self._centroid.textChanged.connect(self._on_change)
        cro.addWidget(self._centroid, 1)
        browse = QPushButton("Browse…")
        browse.clicked.connect(self._browse_centroid)
        cro.addWidget(browse)
        form.addRow("Centroid:", self._centroid_row)

        self._export_row = QWidget()
        er = QHBoxLayout(self._export_row)
        er.setContentsMargins(0, 0, 0, 0)
        self._btn_export = QPushButton("Export engine…")
        self._btn_export.setToolTip(
            "Build the engine for this model now. It is cached per machine, so "
            "the first Record is not the slow one, and an engine is never "
            "copied between machines, because a TensorRT plan is built for one "
            "GPU and one TensorRT version.")
        self._btn_export.clicked.connect(self._export_now)
        er.addWidget(self._btn_export)
        self._export_status = QLabel("")
        self._export_status.setStyleSheet(_MUTED)
        er.addWidget(self._export_status, 1)
        form.addRow("", self._export_row)

        self._summary = QLabel("")
        self._summary.setWordWrap(True)
        self._summary.setStyleSheet(_MUTED)
        outer.addWidget(self._summary)

        self._form = form
        if compact:
            self.setMaximumHeight(260)

    # ── the backend decides which controls exist ─────────────────────────────

    def set_backend(self, backend: str) -> None:
        """Blob, DeepLabCut or SLEAP. A rig runs one at a time, so the row is
        backend-specific rather than a lowest common denominator."""
        self._backend = str(backend or "")
        self._engine.blockSignals(True)
        self._engine.clear()
        if self._backend == "dlc":
            # DeepLabCut-Live's own runners. Fixed at model construction, so
            # changing one rebuilds rather than being quietly ignored.
            for name in ("base", "pytorch", "tensorrt", "lite"):
                self._engine.addItem(name, name)
            self._engine.setToolTip(
                "DeepLabCut-Live runner. base/lite are TensorFlow, tensorrt is "
                "its TensorRT path, pytorch is the DLC3 runtime.")
        else:
            for name in _engines.RUNTIMES:
                self._engine.addItem(name, name)
            self._engine.setToolTip(
                "auto tries tensorrt, then onnx, then native, and says which "
                "it got. native is the toolkit's own runtime; onnx and "
                "tensorrt are exported engines, built once and cached per "
                "machine.")
        self._engine.blockSignals(False)
        self._sync()

    def set_model_path(self, path: str) -> None:
        self._model_path = str(path or "")
        self._sync()

    def set_n_animals(self, n: int, identities=()) -> None:
        """How many animals the run expects, and what they are called.

        Both decide whether crop-track can run at all, so the panel has to know
        both. Without the names the summary refused a run the dialog was about
        to allow, the panel said "give each an identity" while the identities
        sat in the box above it, which is the summary promising something
        other than what the run will do, in the direction that reads as a bug
        rather than a refusal.
        """
        self._n_animals = max(1, int(n or 1))
        self._identities = [str(x) for x in (identities or []) if str(x)]
        self._sync()

    # ── values ───────────────────────────────────────────────────────────────

    def values(self) -> Dict[str, Any]:
        """The config keys the pipeline actually reads. Same names both sides."""
        return {
            "pose_input_mode": self._mode.currentData() or MODE_FULL,
            "pose_input_w": int(self._win_w.value()),
            "pose_input_h": int(self._win_h.value()),
            "pose_crop_conf_min": float(self._conf.value()),
            "pose_crop_good_min": int(self._good.value()),
            "pose_crop_reacquire": bool(self._reacquire.isChecked()),
            "runtime": self._engine.currentData() or "auto",
            "device": self._device.currentText().strip() or "auto",
            "precision": self._precision.currentText() or "fp32",
            "centroid_model_path": self._centroid.text().strip(),
        }

    def load(self, tracking_cfg: Dict[str, Any],
             pose_cfg: Optional[Dict[str, Any]] = None) -> None:
        """Restore from a saved project. Absent keys keep today's behaviour."""
        pose = pose_cfg or {}
        blocked = [self._mode, self._win_w, self._win_h, self._conf,
                   self._good, self._reacquire, self._engine, self._device,
                   self._precision, self._centroid]
        for w in blocked:
            w.blockSignals(True)
        try:
            mode = str(tracking_cfg.get("pose_input_mode", MODE_FULL) or MODE_FULL)
            i = self._mode.findData(mode)
            self._mode.setCurrentIndex(i if i >= 0 else 0)
            self._win_w.setValue(int(tracking_cfg.get("pose_input_w", 0) or 0))
            self._win_h.setValue(int(tracking_cfg.get("pose_input_h", 0) or 0))
            self._conf.setValue(float(tracking_cfg.get("pose_crop_conf_min",
                                                       0.20) or 0.20))
            self._good.setValue(int(tracking_cfg.get("pose_crop_good_min", 3) or 3))
            self._reacquire.setChecked(
                bool(tracking_cfg.get("pose_crop_reacquire", True)))
            want = str(pose.get("runtime")
                       or pose.get("model_type") or "auto")
            j = self._engine.findData(want)
            self._engine.setCurrentIndex(j if j >= 0 else 0)
            self._device.setCurrentText(str(pose.get("device", "auto") or "auto"))
            k = self._precision.findText(str(pose.get("precision", "fp32")
                                             or "fp32").lower())
            self._precision.setCurrentIndex(max(0, k))
            self._centroid.setText(str(pose.get("centroid_model_path", "") or ""))
            self._model_path = str(pose.get("model_path", "") or self._model_path)
        finally:
            for w in blocked:
                w.blockSignals(False)
        self._sync()

    # ── behaviour ────────────────────────────────────────────────────────────

    def _on_change(self, *_):
        self._sync()
        self.changed.emit()

    def _sync(self) -> None:
        """Show only what the current choice uses, and say what will happen."""
        if not hasattr(self, "_mode"):                    # pragma: no cover
            return
        mode = self._mode.currentData() or MODE_FULL
        info = ModelInfo.read(self._model_path)

        # A control the chosen mode cannot use is a question the operator
        # should not be asked, hidden, not greyed.
        self._show_row(self._window_row, mode in (MODE_LETTERBOX, MODE_CROP_TRACK))
        self._show_row(self._crop_row, mode == MODE_CROP_TRACK)
        is_pose = self._backend in ("dlc", "sleap")
        for row in (self._engine, self._device, self._precision):
            self._show_row(row, is_pose)
        self._show_row(self._centroid_row,
                       self._backend == "sleap" and info.needs_centroid)
        self._show_row(self._export_row, self._backend == "sleap"
                       and (self._engine.currentData() in
                            (_engines.RUNTIME_AUTO, *_engines.EXPORTED)))
        self._card.setText(self._card_text(info))
        self._summary.setText(self._summary_text(info, mode))

    def _show_row(self, widget: QWidget, visible: bool) -> None:
        widget.setVisible(visible)
        label = self._form.labelForField(widget)
        if label is not None:
            label.setVisible(visible)

    def _card_text(self, info: ModelInfo) -> str:
        if not self._model_path:
            return ""
        if not info.ok:
            return ("no config found beside this model, its body parts, "
                    "family and input size are unknown")
        lines = [info.summary()]
        lines += ["! " + w for w in info.warnings]
        lines += ["! " + d for d in info.disagreements(n_animals=self._n_animals)]
        return "\n".join(lines)

    def _summary_text(self, info: ModelInfo, mode: str) -> str:
        """What this configuration will actually do, from the real resolvers.

        Generated by the same ``resolve_runtime`` the tracker calls and the
        same refusal the crop mode uses, so the line cannot promise something
        the run will not do.
        """
        if self._backend not in ("dlc", "sleap"):
            return ""
        bits: List[str] = []
        want = self._engine.currentData() or "auto"
        if self._backend == "sleap":
            chosen, why = _engines.resolve_runtime(str(want))
            bits.append(f"engine: {chosen}" + (f", {why}" if why else ""))
        else:
            bits.append(f"engine: {want}")
        if mode == MODE_CROP_TRACK:
            window = ((int(self._win_w.value()), int(self._win_h.value()))
                      if self._win_w.value() and self._win_h.value()
                      else (info.input_size if info.ok else None))
            why = _crop_refusal(info, self._n_animals, window,
                                identities=self._identities)
            bits.append(f"crop-track CANNOT run: {why}" if why
                        else f"crop-track window {window[0]}x{window[1]}")
        elif mode == MODE_LETTERBOX:
            bits.append("frames scaled and padded to one shape")
        return " · ".join(bits)

    # ── actions ──────────────────────────────────────────────────────────────

    def _browse_centroid(self):
        d = QtWidgets.QFileDialog.getExistingDirectory(
            self, "Centroid model folder", self._centroid.text().strip())
        if d:
            self._centroid.setText(d)

    def _export_now(self):
        """Build the engine now rather than at Record.

        Same cache and same key as the run, so the wait is paid once and
        earlier. Reports what it built, including when that is not what was
        asked for.
        """
        if not self._model_path:
            self._export_status.setText("choose a model first")
            return
        vals = self.values()
        self._export_status.setText("exporting…")
        QtWidgets.QApplication.processEvents()
        res = _engines.prewarm(
            self._model_path, str(vals["runtime"]), device=str(vals["device"]),
            precision=str(vals["precision"]),
            centroid_path=str(vals["centroid_model_path"]),
            input_size=ModelInfo.read(self._model_path).input_size)
        if res.ok:
            self._export_status.setText(
                ("built " if res.built else "already built: ") + res.runtime
                + (f": {res.reason}" if res.reason else ""))
        else:
            self._export_status.setText(f"not exported, {res.reason}")
